server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
    template:
      default-topic: library-events
    consumer:
      group-id: taxi-message-topic-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

kafka-consumer-config:
  taxi-message-group-id: taxi-message-topic-consumer
  taxi-message-topic: taxi-messages