server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5556/service
    username: service
    password: service
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    schemas: public
  kafka:
    template:
      default-topic: taxi-messages
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      group-id: taxi-message-topic-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true

kafka-consumer-config:
  taxi-message-group-id: taxi-message-topic-consumer
  taxi-message-topic: taxi-messages
  taxi-message-topic-dlt: taxi-messages-dlt
  taxi-message-retry-attempts: 3
  taxi-message-retry-delay: 1000
  taxi-message-retry-multiplier: 2
